### ISSUE TITLE
Notification/AppInvite is not showing up

### ISSUE THREAD

**Issue by swethadevireddy** [shivasurya/App-invites#3]
Hi Shiva,

Have u tried this recently,I am trying to integrate Fb App invites in my android app.I am able to see the invite being sent but my friends are not receiving notification or app invite.

I tried installing your app, the behavior is same. From your app too I can see the request is sent but not seeing the invite/notification.Would be able to check this once?

Thanks,
Swetha

**Comment by swethadevireddy** [comment]
Sorry got it working..looks like the notification shows up only on android phone not an iphone and also namespace or canavsurl is must ..I should check which is mandatory.

**Comment by shivasurya** [comment]
I hope namespace is mandatory for any App in facebook. I didn't try personally for iPhone Apps moreover, I tried for Playstore link and that doesn't make sense to open google play store on iPhone. So, they would have provided iPhone URL separately while creating App invites facebook app just like creating a deep link for android.

That's it 👍
